abstract class AppConstants {
  static const boxKey = 'local_storage';
  static List<String> fonts  = [
  'Roboto',
  'Open Sans',
  'Montserrat',
  'Poppins',
  'Lato',
  'Raleway',
  'Noto Sans',
  'Source Sans Pro',
  'Nunito',
  'Playfair Display',
  'Merriweather',
  'Oswald',
  'Ubuntu',
  'PT Sans',
  'Droid Sans',
  'Helvetica Neue',
  'Arial',
  'Times New Roman',
  'Georgia',
  'Verdana',
  'Courier New',
  'Comic Sans MS',
  'Impact',
  'Trebuchet MS',
  'Bookman Old Style',
  'Century Gothic',
  'Franklin Gothic Medium',
  'Garamond',
  'Lucida Sans Unicode',
  'Tahoma',
  'Palatino Linotype',
  'Rockwell',
  'Fira Sans',
  'Libre Franklin',
  'Work Sans',
  'Inter',
  'Manrope',
  'Lexend',
  'Saira',
  'Quicksand',
  'Rubik',
  'Poppins',
  'Montserrat',
  'Open Sans',
  'Roboto',
  'Lato',
  'Raleway',
  'Noto Sans',
  'Source Sans Pro',
];


}
